today = ['today','сегодня', 'сьогодні']
tomorrow = ['tomorrow', 'завтра']
monday = ['monday','понедельник', 'пн', 'понеділок']
tuesday = ['tuesday', 'вторник', 'вт', 'вівторок']
wednesday = ['wednesday', 'среда', 'ср', 'середа']
thursday = ['thursday', 'четверг', 'чт', 'четвер']
friday = ['friday','пятница','пт',"п'ятниця"]
saturday = ['saturday', 'суббота', 'сб', 'субота']
sunday = ['sunday','воскресенье','вс','неділя']
next = ['next', 'следующая','след','наступна']
number = ['1','2','3','4','5']
yesterday = ['yesterday','вчера','вчора']

