today = ['today', 'сегодн', 'сьогодн']
tomorrow = ['tomorrow', 'завтра']
monday = ['monday', 'понедельник', 'пн ', 'понеділок']
tuesday = ['tuesday', 'вторник', 'вт ', 'вівтор']
wednesday = ['wednesday', 'среда ', 'среды', 'среду ', 'сред ', 'среде ', 'средой ', 'ср ', 'серед']
thursday = ['thursday', 'чт ', 'четвер']
friday = ['friday', 'пятниц', 'пт ', "п'ятниц", "п'ятниц"]
saturday = ['saturday', 'суббот', 'сб ', 'субот']
sunday = ['sunday', 'воскресен', 'вс ', 'неділ']
next = ['next', 'следующ', 'наступ']
number = ['1', '2', '3', '4', '5']
yesterday = ['yesterday', 'вчера', 'вчора']
right_now = ['now', 'сейчас']
para_input = ['пара', 'пары', 'расписание']


