today = ['today', 'сегодн', 'сьогодн']
tomorrow = ['tomorrow', 'завтра']
monday = ['monday', 'понедельн', 'пн ', 'понеділок']
tuesday = ['tuesday', 'вторн', 'вт ', 'вівтор']
wednesday = ['wednesday', 'сред', 'ср ', 'серед']
thursday = ['thursday', 'чт ', 'четвер']
friday = ['friday', 'пятниц', 'пт ', "п'ятниц", "п'ятниц"]
saturday = ['saturday', 'суббот', 'сб ', 'субот']
sunday = ['sunday', 'воскрес', 'вс ', 'неділ']
next = ['next', 'след', 'наступ']
number = ['1', '2', '3', '4', '5']
yesterday = ['yesterday', 'вчер', 'вчор']
right_now = ['now', 'сейч']
para_input = ['пара', 'пары', 'расписание']

